
name: CI
on:
  push:
    branches-ignore:
      - 'wip/**'
  pull_request:
    # See the docs
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
    branches-ignore:
      - 'wip/**'
  schedule:
    - cron: '0 2 * * 1' # 2am on Monday


jobs:
  do-assignments:
    runs-on: ubuntu-latest

    # TODO perform on mutliple python versions
    # strategy:
    #   matrix:
    #     python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      # TODO setup multiple python versions
      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}

      - name: Set up python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./python/requirements.txt

      - name: Check code formatting
        run: ./python/scripts/check-black-formatting.bash

      - name: Run unittests
        run: |
          cd ./python
          scripts/run-unittests.bash

      - name: Run simulated use cases
        run: |
          cd ./python
          scripts/run-simulated-cases.bash

      - name: Run assignments
        run: |
          cd ./python
          scripts/run-assignments.bash

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

